# Generated by Django 2.1.1 on 2018-09-17 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLdap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('displayname', models.CharField(max_length=100)),
                ('departmentnumber', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('matricula', models.IntegerField(default='')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
